---
postgres:
  host: database
  port: 5432
  user: postgres
  password: postgres

opennms:
  database:
    dbname: opennms
    dbuser: opennms
    dbpass: opennms

  timeseries:
    strategy: newts

  rrd:
    storebyforeignsource: true

  cassandra:
    hostnames: cassandra-01
    keyspace: newts
    port: 9042
    username: cassandra
    password: cassandra
